#!/bin/bash

PPS_CONFIG=~/.config/pps

###################
# private functions
###################

__pps_print_usage() {
	echo "usage:"
	echo "pps <profile>     : activates the defined <profile>"
	echo "pps clear         : clear the actual profile"
}

__pps_init_config() {
	if [ ! -d "${PPS_CONFIG}" ] ; then
		echo "pps config directory ${PPS_CONFIG} does not exist!"
		echo "Creating initial config in directory ${PPS_CONFIG}"
		mkdir -p "${PPS_CONFIG}"
		cp template "${PPS_CONFIG}"/template
	fi
}

__pps_switch-profile() {
	$SHELL "${PPS_CONFIG}/$1"
	export LP_PS1_PREFIX="{$1} "
}

__pps_disable-profile() {
	echo "disabling profile"
    unset LP_PS1_PREFIX
}

listcontains() {
	[[ $1 =~ (^| )$2($| ) ]] && return 0 || return 1
}

######
# main
######

pps() {
	__pps_init_config

	if [ $# -ne 1 ] ; then
		__pps_print_usage
		return 1
	fi

	if [ -f "${PPS_CONFIG}/$1" ] ; then
		__pps_switch-profile "$1"
	else
		if listcontains "clear clean disable" "$1" ; then
			__pps_disable-profile
		else
			echo "Unknown profile: $1"
			__pps_print_usage
			return 1
		fi
	fi
}

